#Compiler flags
CC = g++
CC_FLAGS = -w -std=c++17 -O0

#Source file directories
REFRENCE_SRC_DIR += src/core/*.cpp
REFRENCE_SRC_DIR += src/events/*.cpp

REFRENCE_SRC_DIR += src/graphics/*.cpp
REFRENCE_SRC_DIR += src/graphics/platform/opengl/*.cpp

REFRENCE_SRC_DIR += src/input/*.cpp
REFRENCE_SRC_DIR += src/*.cpp

REFRENCE_SRC_DIR += vendor/imgui/*.cpp

#Include file directories
REFRENCE_INCLUDE_DIRS = -Iinclude -Ivendor

#Library file directories
REFRENCE_LIBRARY_DIRS = -Llib

#Linker flags
REFRENCE_LINKER_FLAGS = -lglfw3dll -lglew32 -lopengl32 -lImm32

#Outputs
REFRENCE_EXE_OUTPUT = build/sandbox.exe

compile:
	$(CC) $(CC_FLAGS) $(REFRENCE_SRC_DIR) -o $(REFRENCE_EXE_OUTPUT) $(REFRENCE_INCLUDE_DIRS) $(REFRENCE_LIBRARY_DIRS) $(REFRENCE_LINKER_FLAGS)

run:
	$(REFRENCE_EXE_OUTPUT)

